"""Overpass POI type definitions — known category values and noise blacklist."""

CATEGORIES: dict[str, set[str]] = {
    "amenity": {
        # Food & drink
        "restaurant",
        "cafe",
        "bar",
        "pub",
        "fast_food",
        "ice_cream",
        "biergarten",
        "food_court",
        "juice_bar",
        # Entertainment & nightlife
        "nightclub",
        "cinema",
        "theatre",
        "arts_centre",
        "events_venue",
        "music_venue",
        "concert_hall",
        "casino",
        "stripclub",
        "hookah_lounge",
        "karaoke_box",
        # Cultural & religious
        "place_of_worship",
        "monastery",
        "library",
        "public_bookcase",
        "planetarium",
        "camera_obscura",
        "archive",
        # Civic & public
        "townhall",
        "courthouse",
        "community_centre",
        "fire_station",
        "police",
        "hospital",
        "clinic",
        "fountain",
        "clock",
        "marketplace",
        "grave_yard",
        # Education
        "university",
        "college",
        "school",
        "kindergarten",
        "language_school",
        # Transport & services
        "ferry_terminal",
        "bus_station",
        "boat_rental",
        "bicycle_rental",
        "parking",
        "parking_entrance",
        "bicycle_parking",
        "taxi",
        "car_rental",
        "car_sharing",
        "fuel",
        "charging_station",
        # Finance & postal
        "bank",
        "atm",
        "bureau_de_change",
        "post_office",
        "money_transfer",
        # Health & wellness
        "pharmacy",
        "dentist",
        "doctors",
        "veterinary",
        "public_bath",
        # Other
        "studio",
        "coworking_space",
        "social_facility",
        "conference_centre",
        "internet_cafe",
        "love_hotel",
        "brothel",
        "drinking_water",
        "toilets",
        "vending_machine",
        "recycling",
        "shelter",
        "telephone",
    },
    "shop": {
        # Food & drink
        "supermarket",
        "convenience",
        "bakery",
        "pastry",
        "butcher",
        "greengrocer",
        "deli",
        "seafood",
        "cheese",
        "chocolate",
        "confectionery",
        "tea",
        "coffee",
        "wine",
        "alcohol",
        "beverages",
        "ice_cream",
        # Fashion & accessories
        "clothes",
        "shoes",
        "jewelry",
        "fashion_accessories",
        "bag",
        "watches",
        "leather",
        "boutique",
        "perfumery",
        "cosmetics",
        "beauty",
        "hairdresser",
        "tattoo",
        "massage",
        "optician",
        # Culture & hobbies
        "books",
        "art",
        "music",
        "musical_instrument",
        "antiques",
        "craft",
        "collector",
        "pottery",
        "candles",
        "games",
        "toys",
        "second_hand",
        "charity",
        "gift",
        "ticket",
        # Home & interior
        "furniture",
        "interior_decoration",
        "houseware",
        # Electronics & tech
        "electronics",
        "mobile_phone",
        "computer",
        "hifi",
        "camera",
        # Everyday services
        "laundry",
        "dry_cleaning",
        "copyshop",
        "photo",
        "tailor",
        "florist",
        # General & other
        "department_store",
        "mall",
        "variety_store",
        "hardware",
        "sports",
        "outdoor",
        "stationery",
        "newsagent",
        "travel_agency",
        "bicycle",
        "motorcycle",
        "pet",
        "health_food",
        "kiosk",
        "tobacco",
        "cannabis",
        "e-cigarette",
        "bookmaker",
        "pawnbroker",
        "chemist",
        "fabric",
        "carpet",
        "estate_agent",
        "car_repair",
        "hearing_aids",
        "medical_supply",
        "funeral_directors",
        "religion",
        "erotic",
        "yes",
    },
    "tourism": {
        "museum",
        "gallery",
        "hotel",
        "hostel",
        "guest_house",
        "apartment",
        "motel",
        "attraction",
        "viewpoint",
        "artwork",
        "information",
        "aquarium",
        "zoo",
        "theme_park",
    },
    "leisure": {
        "park",
        "garden",
        "playground",
        "bandstand",
        "stadium",
        "sports_centre",
        "fitness_centre",
        "swimming_pool",
        "marina",
        "sauna",
        "escape_game",
        "amusement_arcade",
        "adult_gaming_centre",
        "dance",
        "bowling_alley",
        "miniature_golf",
        "pitch",
        "outdoor_seating",
        "nature_reserve",
        "dog_park",
    },
    "historic": {
        "memorial",
        "monument",
        "archaeological_site",
        "castle",
        "ruins",
        "citywalls",
        "city_gate",
        "tomb",
        "building",
        "battlefield",
        "manor",
        "tower",
        "house",
        "bridge",
        "fort",
        "church",
        "monastery",
        "wayside_shrine",
        "wayside_cross",
        "district",
        "heritage",
        "boundary_stone",
        "yes",
        "wall",
        "fountain",
        "cannon",
        "milestone",
        "railway_station",
        "townhall",
    },
}

# (category, value) tuples to REJECT — never interesting for a city guide.
# Stats (70 test locations, r=500): 47 types, 4326 / 33035 named POIs filtered (13%).
OVERPASS_NOISE_TYPES: frozenset[tuple[str, str]] = frozenset(
    {
        # amenity — transport/utility clutter
        ("amenity", "parking"),
        ("amenity", "parking_entrance"),
        ("amenity", "bicycle_parking"),
        ("amenity", "motorcycle_parking"),
        ("amenity", "atm"),
        ("amenity", "charging_station"),
        ("amenity", "vending_machine"),
        ("amenity", "recycling"),
        ("amenity", "toilets"),
        ("amenity", "drinking_water"),
        ("amenity", "bench"),
        ("amenity", "waste_basket"),
        ("amenity", "parcel_locker"),
        ("amenity", "car_wash"),
        ("amenity", "car_sharing"),
        ("amenity", "telephone"),
        ("amenity", "bicycle_rental"),
        ("amenity", "car_rental"),
        ("amenity", "fuel"),
        ("amenity", "shelter"),
        ("amenity", "photo_booth"),
        ("amenity", "driving_school"),
        ("amenity", "taxi"),
        ("amenity", "police"),
        # amenity — medical / health
        ("amenity", "dentist"),
        ("amenity", "doctors"),
        ("amenity", "clinic"),
        ("amenity", "pharmacy"),
        ("amenity", "veterinary"),
        # amenity — education
        ("amenity", "school"),
        ("amenity", "kindergarten"),
        # amenity — social
        ("amenity", "social_facility"),
        # shop — empty storefronts & utilitarian
        ("shop", "vacant"),
        ("shop", "shoe_repair"),
        ("shop", "locksmith"),
        ("shop", "mobile_phone_accessories"),
        ("shop", "car_repair"),
        ("shop", "estate_agent"),
        ("shop", "dry_cleaning"),
        ("shop", "hearing_aids"),
        ("shop", "funeral_directors"),
        ("shop", "medical_supply"),
        # shop — services & generic retail
        ("shop", "hairdresser"),
        ("shop", "beauty"),
        ("shop", "optician"),
        ("shop", "chemist"),
        ("shop", "mobile_phone"),
        ("shop", "laundry"),
        ("shop", "copyshop"),
        ("shop", "computer"),
        # amenity — finance (historic buildings come via historic= tags)
        ("amenity", "bank"),
        # tourism — info boards / kiosks
        ("tourism", "information"),
        # leisure — generic sports fields
        ("leisure", "pitch"),
    }
)
