"""Wikidata whitelist — allowed item types for geo-enrichment.

Used by city_guide.wikidata for filtering SPARQL results, and by
scan_wikidata_types.py for evaluating whitelist coverage.

When adding new types:
  1. Run: uv run python scan_wikidata_types.py
  2. Review rejected items for false negatives
  3. Add missing types here
  4. Re-run with --summary to verify pass rate improved
"""

# "building" is too generic (87x in test scan) — only kept if it has enrichment facts
WIKIDATA_BUILDING_TYPE = "building"

WIKIDATA_ALLOWED_TYPES: frozenset[str] = frozenset(
    {
        # Food & drink
        "pub",
        "restaurant",
        "café",
        "cocktail lounge",
        "brewery",
        "bakery",
        "tavern",
        "fast food restaurant",
        # Entertainment & nightlife
        "nightclub",
        "movie theater",
        "theatre building",
        "music venue",
        "sports venue",
        "arena",
        "stadium",
        "bandstand",
        "jazz club",
        "bar",
        "gay bar",
        "piano bar",
        "venue",
        "amusement park",
        # Religious
        "church building",
        "Catholic church building",
        "Catholic cathedral",
        "Eastern Orthodox church building",
        "mosque",
        "chapel",
        "minor basilica",
        "madrasa",
        "priory",
        "Sufi lodge",
        "temple",
        "Roman temple",
        "synagogue",
        "Shinto shrine",
        "Buddhist temple",
        "wat",
        "monastery",
        "oratory",
        "parish church",
        "former church",
        "holy well",
        "Orthodox chapel",
        # Historical
        "castle",
        "kremlin",
        "palace",
        "Palazzo",
        "fortified tower",
        "triumphal arch",
        "ruins",
        "historic site",
        "historic building",
        "archaeological site",
        "historic house museum",
        "execution site",
        "house",
        "mansion",
        "catacombs",
        "national monument",
        "cultural property",
        "heritage site",
        "architectural heritage monument",
        "cultural heritage",
        "battle",
        "siege",
        # Monuments & art
        "statue",
        "sculpture",
        "monument",
        "memorial",
        "war memorial",
        "fountain",
        "obelisk",
        "mausoleum",
        "tomb",
        "work of art",
        "relief sculpture",
        "sundial",
        "astronomical clock",
        "colossal statue",
        "Maria column",
        "Celtic cross",
        "LGBT monument or memorial",
        "commemorative plaque",
        "Stolperstein",
        # Cultural institutions
        "museum",
        "art museum",
        "art gallery",
        "local museum",
        "technology museum",
        "artist museum",
        "maritime museum",
        "craft museum",
        "contemporary art museum",
        "private museum",
        "library",
        "public library",
        "national library",
        "special library",
        "academic library",
        "archives",
        "planetarium",
        "recording studio",
        # Notable infrastructure
        "bridge",
        "suspension bridge",
        "footbridge",
        "tower",
        "skyscraper",
        "water tower",
        "department store",
        "market",
        "street market",
        "flea market",
        "shopping arcade",
        "shopping center",
        "shop",
        "retail building",
        "hotel",
        "guest house",
        "hostel",
        "square",
        "Rathaus",
        "arcade",
        # Education
        "school",
        "higher education institution",
        "collegiate university",
        "university building",
        "military school",
        # Civic & public
        "hospital",
        "fire station",
        "police station",
        "city hall",
        "drill hall",
        "prison",
        # Green spaces & outdoors
        "park",
        "urban park",
        "garden square",
        "rose garden",
        "cemetery",
        "scenic viewpoint",
        "botanical garden",
        # Maritime & transport
        "pier",
        "wharf",
        "dock",
        "harbor",
        "lighthouse",
        "railway station",
        "metro station",
        "warehouse",
        # Architecture
        "architectural structure",
        "architectural landmark",
        "building complex",
        "gate",
        "city gate",
        "arch",
        "defensive wall",
        "wall",
        "nymphaeum",
        "hammam",
        "cistern",
        "aqueduct",
        "neck gable building",
        "building with clock gable",
        # Residential (listed / historic)
        "residential building",
        "apartment",
        "tenement",
        "kamienica",
        # Areas
        "neighborhood",
        # Other notable
        "factory",
        "mint",
        "air-raid shelter",
        "World Heritage Site",
        "tourist attraction",
        "bookstore",
        "record shop",
    }
)
